default_platform(:ios)

platform :ios do
  desc "Run tests"
  lane :test do
    run_tests(scheme: "Claw")
  end

  desc "Build and upload to TestFlight"
  lane :beta do
    increment_build_number
    build_app(scheme: "Claw")
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end
